\LoadClass[a4paper,12pt]{report}
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{reportex}[2014/10/07 A template for LaTeX reports]


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  PACKAGES  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Colors
\RequirePackage[% Add colors
  svgnames,     % 150 colors
  table         % Add colors to tables
]{xcolor}

%% Miscellaneous
\RequirePackage[utf8]{inputenc}  % Special characters
\RequirePackage{graphicx}        % Images
\RequirePackage{mathtools}       % Maths
\RequirePackage{listings}        % Codes